In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv('uscrime.txt',delim_whitespace=True)

In [3]:
dataset.head()

M  So    Ed   Po1   Po2     LF    M.F  Pop    NW     U1   U2  Wealth  \
0  15.1   1   9.1   5.8   5.6  0.510   95.0   33  30.1  0.108  4.1    3940   
1  14.3   0  11.3  10.3   9.5  0.583  101.2   13  10.2  0.096  3.6    5570   
2  14.2   1   8.9   4.5   4.4  0.533   96.9   18  21.9  0.094  3.3    3180   
3  13.6   0  12.1  14.9  14.1  0.577   99.4  157   8.0  0.102  3.9    6730   
4  14.1   0  12.1  10.9  10.1  0.591   98.5   18   3.0  0.091  2.0    5780   

   Ineq      Prob     Time  Crime  
0  26.1  0.084602  26.2011    791  
1  19.4  0.029599  25.2999   1635  
2  25.0  0.083401  24.3006    578  
3  16.7  0.015801  29.9012   1969  
4  17.4  0.041399  21.2998   1234

In [4]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values


In [5]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

C:\Users\SAURABH\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
# No need to scale or hotencode

In [8]:
#sc_x=StandardScaler()

In [9]:
#x_train=sc_x.fit_transform(x_train)
#x_test=sc_x.transform(x_test)

In [10]:
from sklearn.tree import DecisionTreeRegressor

In [11]:
regressor=DecisionTreeRegressor()

In [12]:
regressor.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [13]:
y_pred=regressor.predict(x_test)

In [14]:
y_pred

array([ 831., 1030., 1030., 1030., 1216.,  880.,  849.,  439.,  849.,
        373.,  696.,  849.])

In [15]:
y_test

array([ 826, 1993,  849,  968, 1555,  705,  539,  455,  342,  542,  511,
       1234], dtype=int64)

In [16]:
from sklearn.ensemble import RandomForestClassifier

C:\Users\SAURABH\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [17]:
Regressor=RandomForestClassifier(n_estimators=500)

In [18]:
Regressor.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [19]:
Y_pred=Regressor.predict(x_test)

In [20]:
Y_pred

array([ 791, 1969,  963,  373, 1151,  880,  742,  946,  880,  373,  742,
        880], dtype=int64)

In [21]:
y_test

array([ 826, 1993,  849,  968, 1555,  705,  539,  455,  342,  542,  511,
       1234], dtype=int64)

In [22]:
from sklearn.metrics import mean_squared_error

In [23]:
np.sqrt(mean_squared_error(y_test,y_pred))

373.49263714295626

In [24]:
np.sqrt(mean_squared_error(y_test,Y_pred))

334.3694314178057

In [25]:
# increasing the number of n_estimatores i.e, no of forests improves the performance.

In [ ]:
0