In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Applying PCA for supervised learning is fundamentally in correct

In [91]:
dataset=pd.read_csv('germancredit.txt',delim_whitespace=True,header=None)

In [92]:
dataset.head()

0   1    2    3     4    5    6   7    8     9  ...    11  12    13    14  \
0  A11   6  A34  A43  1169  A65  A75   4  A93  A101 ...  A121  67  A143  A152   
1  A12  48  A32  A43  5951  A61  A73   2  A92  A101 ...  A121  22  A143  A152   
2  A14  12  A34  A46  2096  A61  A74   2  A93  A101 ...  A121  49  A143  A152   
3  A11  42  A32  A42  7882  A61  A74   2  A93  A103 ...  A122  45  A143  A153   
4  A11  24  A33  A40  4870  A61  A73   3  A93  A101 ...  A124  53  A143  A153   

  15    16 17    18    19 20  
0  2  A173  1  A192  A201  1  
1  1  A173  1  A191  A201  2  
2  1  A172  2  A191  A201  1  
3  1  A173  2  A191  A201  1  
4  2  A173  2  A191  A201  2  

[5 rows x 21 columns]

In [93]:
dataset.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            19, 20],
           dtype='int64')

In [94]:
dataset = dataset.iloc[:,[0,2,3,5,6,8,9,11,13,14,16,18,19,1,4,7,10,12,15,17,20]]
dataset.columns=list(range(0,21))
dataset.head()

0    1    2    3    4    5     6     7     8     9  ...    11    12  13  \
0  A11  A34  A43  A65  A75  A93  A101  A121  A143  A152 ...  A192  A201   6   
1  A12  A32  A43  A61  A73  A92  A101  A121  A143  A152 ...  A191  A201  48   
2  A14  A34  A46  A61  A74  A93  A101  A121  A143  A152 ...  A191  A201  12   
3  A11  A32  A42  A61  A74  A93  A103  A122  A143  A153 ...  A191  A201  42   
4  A11  A33  A40  A61  A73  A93  A101  A124  A143  A153 ...  A191  A201  24   

     14  15  16  17  18  19  20  
0  1169   4   4  67   2   1   1  
1  5951   2   2  22   1   1   2  
2  2096   2   3  49   1   2   1  
3  7882   2   4  45   1   2   1  
4  4870   3   4  53   2   2   2  

[5 rows x 21 columns]

# Different type f encoding

In [95]:
char_cols = dataset.dtypes.pipe(lambda x: x[x == 'object']).index

for c in char_cols:
    dataset[c] = pd.factorize(dataset[c])[0]

In [96]:
dataset.head()

0   1   2   3   4   5   6   7   8   9  ...  11  12  13    14  15  16  17  \
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   6  1169   4   4  67   
1   1   1   0   1   1   1   0   0   0   0 ...   1   0  48  5951   2   2  22   
2   2   0   1   1   2   0   0   0   0   0 ...   1   0  12  2096   2   3  49   
3   0   1   2   1   2   0   1   1   0   1 ...   1   0  42  7882   2   4  45   
4   0   2   3   1   1   0   0   2   0   1 ...   1   0  24  4870   3   4  53   

   18  19  20  
0   2   1   1  
1   1   1   2  
2   1   2   1  
3   1   2   1  
4   2   2   2  

[5 rows x 21 columns]

In [97]:
ohe = pd.get_dummies(dataset, columns=[0,1,2,3,4,5,6,7,8,9,10,11,12])

In [98]:
ohe.head()

13    14  15  16  17  18  19  20  0_0  0_1  ...   9_1  9_2  10_0  10_1  \
0   6  1169   4   4  67   2   1   1    1    0  ...     0    0     1     0   
1  48  5951   2   2  22   1   1   2    0    1  ...     0    0     1     0   
2  12  2096   2   3  49   1   2   1    0    0  ...     0    0     0     1   
3  42  7882   2   4  45   1   2   1    1    0  ...     1    0     1     0   
4  24  4870   3   4  53   2   2   2    1    0  ...     1    0     1     0   

   10_2  10_3  11_0  11_1  12_0  12_1  
0     0     0     1     0     1     0  
1     0     0     0     1     1     0  
2     0     0     0     1     1     0  
3     0     0     0     1     1     0  
4     0     0     0     1     1     0  

[5 rows x 62 columns]

In [99]:
result=ohe[20]
ohe.drop(columns=20).head()


13    14  15  16  17  18  19  0_0  0_1  0_2  ...   9_1  9_2  10_0  10_1  \
0   6  1169   4   4  67   2   1    1    0    0  ...     0    0     1     0   
1  48  5951   2   2  22   1   1    0    1    0  ...     0    0     1     0   
2  12  2096   2   3  49   1   2    0    0    1  ...     0    0     0     1   
3  42  7882   2   4  45   1   2    1    0    0  ...     1    0     1     0   
4  24  4870   3   4  53   2   2    1    0    0  ...     1    0     1     0   

   10_2  10_3  11_0  11_1  12_0  12_1  
0     0     0     1     0     1     0  
1     0     0     0     1     1     0  
2     0     0     0     1     1     0  
3     0     0     0     1     1     0  
4     0     0     0     1     1     0  

[5 rows x 61 columns]

In [100]:
dataset=pd.concat([ohe,result],axis=1)

In [101]:
dataset.columns=list(range(0,len(dataset.columns)))

In [102]:
dataset.head()

0     1   2   3   4   5   6   7   8   9  ...  53  54  55  56  57  58  59  \
0   6  1169   4   4  67   2   1   1   1   0 ...   0   1   0   0   0   1   0   
1  48  5951   2   2  22   1   1   2   0   1 ...   0   1   0   0   0   0   1   
2  12  2096   2   3  49   1   2   1   0   0 ...   0   0   1   0   0   0   1   
3  42  7882   2   4  45   1   2   1   1   0 ...   0   1   0   0   0   0   1   
4  24  4870   3   4  53   2   2   2   1   0 ...   0   1   0   0   0   0   1   

   60  61  62  
0   1   0   1  
1   1   0   2  
2   1   0   1  
3   1   0   1  
4   1   0   2  

[5 rows x 63 columns]

In [103]:
# Let us not split into test train dataset

In [104]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [105]:
from sklearn.decomposition import  PCA

In [125]:
pca=PCA(n_components=5)

In [126]:
principal_components=pca.fit_transform(x)
principalDf=pd.DataFrame(principal_components,columns=['PC1','PC2','PC3','PC4','PC5'])

In [108]:
principalDf=pd.concat([principalDf,dataset.iloc[:,62]],axis=1)
principalDf

PC1        PC2        PC3       PC4       PC5  62
0   -2102.286190  32.934814   3.361580 -0.706261 -0.902553   1
1    2679.802926 -17.322428 -17.054074  1.234910  1.281974   2
2   -1175.275759  14.438554   3.269403  0.606706  0.906569   1
3    4610.783140   7.120523 -10.214575 -0.506309  1.313593   1
4    1598.746914  17.197031  -1.985093 -0.769788  0.245445   2
5    5783.761733  -1.175733   0.582821 -1.074731  0.629502   1
6    -436.245920  16.476290  -7.350246 -0.471361  0.559615   1
7    3676.769316  -2.002035  -4.960469  0.946710  0.497130   1
8    -212.277679  26.569207   3.648086  0.127531  1.171001   1
9    1962.758172  -8.385762  -2.418845  0.435833 -1.333926   2
10  -1976.276127  -9.545410   5.444499  1.271729 -0.198153   2
11   1036.809064 -15.886399 -21.816771 -1.150722  1.339182   2
12  -1704.277248 -12.383970   6.773613  1.901791  1.282536   1
13  -2072.239186  22.805250 -12.979583 -0.536323 -0.122585   2
14  -1868.268014  -7.019550   2.257025 -1.129440  1.661517   1
15  -1989.243272  -4.794901  -7.698411  0.729238 -0.539349   2
16   -847.244543  16.358670  -8.485764 -0.806863 -0.495640   1
17   4800.747817 -10.316346   5.672135 -0.315894  0.216304   1
18   9307.718083  11.010852  20.006681  0.058116 -2.737193   2
19    158.749116  -4.974942  -1.813830  0.599886 -0.437682   1
20  -1137.284098  14.044098   6.397158 -1.120837 -1.080111   1
21   -624.294436  10.762787  11.512995  0.127455  0.771577   1
22  -1030.281646  13.861461   5.852905  0.507337  1.953145   1
23  -1467.275380   9.423615   3.335013 -0.809869  0.264424   1
24  -1202.284040  -7.893297   9.316585  1.629595  0.234481   1
25  -1897.290724   2.449209   9.643223  1.305144  1.420073   1
26  -2845.287321   5.118457   6.447991 -1.184279 -0.677570   1
27  -2862.270789   6.929673   0.024976 -0.005848  0.559296   1
28   -856.292373   0.647224  11.685852  0.909014 -0.573656   1
29   3564.837374  21.237913 -33.974649 -0.041055  0.941500   2
..           ...        ...        ...       ...       ...  ..
970 -1757.269437 -12.901229   3.561580  0.359063 -1.052789   1
971  4121.736616   8.240659   6.601279 -0.198283  1.604544   1
972 -2078.242894  -7.698526  -7.287985 -0.921022  2.875795   2
973  4025.831947  -5.167676 -27.924216 -1.206944  0.110842   2
974  -440.232601  -4.326700  -9.677959  0.688408 -0.871498   1
975 -2013.239808  19.798695 -12.219699  0.923751  0.828796   1
976 -2518.285049  29.737291   2.914093  1.221809  1.262633   1
977  -844.261964   6.569619  -0.590409  0.658584 -1.168410   1
978  -733.245686  10.498992  -7.099480 -0.896785 -0.444667   2
979 -2007.267879 -10.059570   2.439576  0.626066  1.065668   2
980  5114.749814  13.340346   2.206313  1.443200  0.109145   2
981  1572.808540  -6.857223 -22.008363  0.849700  0.270832   2
982  -348.257222  -7.613359   0.444645  2.087390  1.397909   1
983  4957.763355 -10.406072   0.034014  0.875721  0.316308   2
984 -1243.245959  -6.451467  -5.274394  1.031455  0.939236   1
985 -1838.268747  -9.959216   2.809576 -0.931513 -0.528327   1
986  3017.787201  -5.307419 -12.236352  2.256766  0.724256   1
987 -1862.268701  28.745033  -2.242523  0.215878  1.592153   1
988  3307.737630  -5.823339   6.842702 -0.095895 -1.854612   1
989 -1528.242784  11.154818  -9.357244  1.046954 -0.831804   1
990   293.717413   3.115961   9.330305  1.877293 -0.006844   1
991 -1702.267997  -1.000158   1.514700 -1.346887 -0.682338   1
992 -1335.262564 -12.266678   1.610642 -1.333306  1.440069   1
993   687.779101  -7.916009 -12.052013 -0.369819 -0.705164   1
994  -881.276745  15.528367   3.767127 -0.189807 -1.214022   1
995 -1535.276994  -3.387849   5.519059 -1.022774  0.457080   1
996   585.764771   2.972643  -8.232041 -0.980098 -0.451071   1
997 -2467.272766   3.182798   1.720146 -1.188746 -0.657294   1
998 -1426.190188 -17.144877 -25.266992 -1.488099  0.280986   2
999  1304.800576 -12.261372 -18.711352 -0.992549  0.808749   1

[1000 rows x 6 columns]

In [109]:
x=principalDf.iloc[:,:-1].values
y=principalDf.iloc[:,-1].values

In [110]:
from sklearn.cross_validation import train_test_split

In [111]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

from sklearn.preprocessing import LabelEncoder # here we saw that Label encoder did not work for multiple column at once.




from sklearn.preprocessing import OneHotEncoder # used dummies instead



In [112]:
from sklearn.linear_model import LogisticRegression

In [113]:
regressor=LogisticRegression(class_weight='balanced')

In [114]:
regressor.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [115]:
THRESHOLD = 0.2
preds = np.where(regressor.predict_proba(x_test)[:,1] > THRESHOLD, 1, 2)

In [116]:
y_pred=regressor.predict(x_test)

In [117]:
from sklearn.metrics import confusion_matrix

In [118]:
cm=confusion_matrix(y_test,preds)

In [119]:
cm

array([[172,   2],
       [ 76,   0]], dtype=int64)

In [122]:
cm2=confusion_matrix(y_test,y_pred)
cm2

array([[103,  71],
       [ 36,  40]], dtype=int64)

In [127]:
# here PCA has been taken but since we have onehotencoded , I this this would be in appropriate.

In [1]:
print(__doc__)


# Code source: Gaël Varoquaux
# License: BSD 3 clause

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


from sklearn import decomposition
from sklearn import datasets

np.random.seed(5)

centers = [[1, 1], [-1, -1], [1, -1]]
iris = datasets.load_iris()
X = iris.data
y = iris.target

fig = plt.figure(1, figsize=(4, 3))
plt.clf()
ax = Axes3D(fig, rect=[0, 0, .95, 1], elev=48, azim=134)

plt.cla()
pca = decomposition.PCA(n_components=3)
pca.fit(X)
X = pca.transform(X)

for name, label in [('Setosa', 0), ('Versiour', 1), ('Virginica', 2)]:
    ax.text3D(X[y == label, 0].mean(),
              X[y == label, 1].mean() + 1.5,
              X[y == label, 2].mean(), name,
              horizontalalignment='center',
              bbox=dict(alpha=.5, edgecolor='w', facecolor='w'))
# Reorder the labels to have colors matching the cluster results
y = np.choose(y, [1, 2, 0]).astype(np.float)
ax.scatter(X[:, 0], X[:, 1], X[:, 2], c=y, cmap=plt.cm.nipy_spectral,
           edgecolor='k')

ax.w_xaxis.set_ticklabels([])
ax.w_yaxis.set_ticklabels([])
ax.w_zaxis.set_ticklabels([])

plt.show()

Automatically created module for IPython interactive environment


<Figure size 400x300 with 1 Axes>

In [2]:
X

array([[-2.68420713,  0.32660731, -0.02151184],
       [-2.71539062, -0.16955685, -0.20352143],
       [-2.88981954, -0.13734561,  0.02470924],
       [-2.7464372 , -0.31112432,  0.03767198],
       [-2.72859298,  0.33392456,  0.0962297 ],
       [-2.27989736,  0.74778271,  0.17432562],
       [-2.82089068, -0.08210451,  0.26425109],
       [-2.62648199,  0.17040535, -0.01580151],
       [-2.88795857, -0.57079803,  0.02733541],
       [-2.67384469, -0.1066917 , -0.1915333 ],
       [-2.50652679,  0.65193501, -0.069275  ],
       [-2.61314272,  0.02152063,  0.10765035],
       [-2.78743398, -0.22774019, -0.20032779],
       [-3.22520045, -0.50327991,  0.06841363],
       [-2.64354322,  1.1861949 , -0.1445057 ],
       [-2.38386932,  1.34475434,  0.28373066],
       [-2.6225262 ,  0.81808967,  0.14531599],
       [-2.64832273,  0.31913667,  0.03339425],
       [-2.19907796,  0.87924409, -0.11452146],
       [-2.58734619,  0.52047364,  0.21957209],
       [-2.3105317 ,  0.39786782, -0.233