In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [252]:
dataset=pd.read_csv('germancredit.txt',delim_whitespace=True,header=None)

In [253]:
dataset.head()

0   1    2    3     4    5    6   7    8     9  ...    11  12    13    14  \
0  A11   6  A34  A43  1169  A65  A75   4  A93  A101 ...  A121  67  A143  A152   
1  A12  48  A32  A43  5951  A61  A73   2  A92  A101 ...  A121  22  A143  A152   
2  A14  12  A34  A46  2096  A61  A74   2  A93  A101 ...  A121  49  A143  A152   
3  A11  42  A32  A42  7882  A61  A74   2  A93  A103 ...  A122  45  A143  A153   
4  A11  24  A33  A40  4870  A61  A73   3  A93  A101 ...  A124  53  A143  A153   

  15    16 17    18    19 20  
0  2  A173  1  A192  A201  1  
1  1  A173  1  A191  A201  2  
2  1  A172  2  A191  A201  1  
3  1  A173  2  A191  A201  1  
4  2  A173  2  A191  A201  2  

[5 rows x 21 columns]

In [254]:
dataset.columns

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
            19, 20],
           dtype='int64')

In [255]:
dataset = dataset.iloc[:,[0,2,3,5,6,8,9,11,13,14,16,18,19,1,4,7,10,12,15,17,20]]
dataset.columns=list(range(0,21))
dataset.head()

0    1    2    3    4    5     6     7     8     9  ...    11    12  13  \
0  A11  A34  A43  A65  A75  A93  A101  A121  A143  A152 ...  A192  A201   6   
1  A12  A32  A43  A61  A73  A92  A101  A121  A143  A152 ...  A191  A201  48   
2  A14  A34  A46  A61  A74  A93  A101  A121  A143  A152 ...  A191  A201  12   
3  A11  A32  A42  A61  A74  A93  A103  A122  A143  A153 ...  A191  A201  42   
4  A11  A33  A40  A61  A73  A93  A101  A124  A143  A153 ...  A191  A201  24   

     14  15  16  17  18  19  20  
0  1169   4   4  67   2   1   1  
1  5951   2   2  22   1   1   2  
2  2096   2   3  49   1   2   1  
3  7882   2   4  45   1   2   1  
4  4870   3   4  53   2   2   2  

[5 rows x 21 columns]

# Different type f encoding

In [256]:
char_cols = dataset.dtypes.pipe(lambda x: x[x == 'object']).index

for c in char_cols:
    dataset[c] = pd.factorize(dataset[c])[0]

In [257]:
dataset.head()

0   1   2   3   4   5   6   7   8   9  ...  11  12  13    14  15  16  17  \
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   6  1169   4   4  67   
1   1   1   0   1   1   1   0   0   0   0 ...   1   0  48  5951   2   2  22   
2   2   0   1   1   2   0   0   0   0   0 ...   1   0  12  2096   2   3  49   
3   0   1   2   1   2   0   1   1   0   1 ...   1   0  42  7882   2   4  45   
4   0   2   3   1   1   0   0   2   0   1 ...   1   0  24  4870   3   4  53   

   18  19  20  
0   2   1   1  
1   1   1   2  
2   1   2   1  
3   1   2   1  
4   2   2   2  

[5 rows x 21 columns]

In [258]:
ohe = pd.get_dummies(dataset, columns=[0,1,2,3,4,5,6,7,8,9,10,11,12])

In [259]:
ohe.head()

13    14  15  16  17  18  19  20  0_0  0_1  ...   9_1  9_2  10_0  10_1  \
0   6  1169   4   4  67   2   1   1    1    0  ...     0    0     1     0   
1  48  5951   2   2  22   1   1   2    0    1  ...     0    0     1     0   
2  12  2096   2   3  49   1   2   1    0    0  ...     0    0     0     1   
3  42  7882   2   4  45   1   2   1    1    0  ...     1    0     1     0   
4  24  4870   3   4  53   2   2   2    1    0  ...     1    0     1     0   

   10_2  10_3  11_0  11_1  12_0  12_1  
0     0     0     1     0     1     0  
1     0     0     0     1     1     0  
2     0     0     0     1     1     0  
3     0     0     0     1     1     0  
4     0     0     0     1     1     0  

[5 rows x 62 columns]

In [260]:
result=ohe[20]
ohe.drop(columns=20).head()


13    14  15  16  17  18  19  0_0  0_1  0_2  ...   9_1  9_2  10_0  10_1  \
0   6  1169   4   4  67   2   1    1    0    0  ...     0    0     1     0   
1  48  5951   2   2  22   1   1    0    1    0  ...     0    0     1     0   
2  12  2096   2   3  49   1   2    0    0    1  ...     0    0     0     1   
3  42  7882   2   4  45   1   2    1    0    0  ...     1    0     1     0   
4  24  4870   3   4  53   2   2    1    0    0  ...     1    0     1     0   

   10_2  10_3  11_0  11_1  12_0  12_1  
0     0     0     1     0     1     0  
1     0     0     0     1     1     0  
2     0     0     0     1     1     0  
3     0     0     0     1     1     0  
4     0     0     0     1     1     0  

[5 rows x 61 columns]

In [221]:
dataset=pd.concat([ohe,result],axis=1)

In [228]:
dataset.columns=list(range(0,len(dataset.columns)))

In [262]:
dataset.head()

0   1   2   3   4   5   6   7   8   9  ...  11  12  13    14  15  16  17  \
0   0   0   0   0   0   0   0   0   0   0 ...   0   0   6  1169   4   4  67   
1   1   1   0   1   1   1   0   0   0   0 ...   1   0  48  5951   2   2  22   
2   2   0   1   1   2   0   0   0   0   0 ...   1   0  12  2096   2   3  49   
3   0   1   2   1   2   0   1   1   0   1 ...   1   0  42  7882   2   4  45   
4   0   2   3   1   1   0   0   2   0   1 ...   1   0  24  4870   3   4  53   

   18  19  20  
0   2   1   1  
1   1   1   2  
2   1   2   1  
3   1   2   1  
4   2   2   2  

[5 rows x 21 columns]

In [280]:
len(dataset[dataset[20]==1].index)

700

In [133]:
# Let us not split into test train dataset

In [263]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [264]:
from sklearn.cross_validation import train_test_split

In [265]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

from sklearn.preprocessing import LabelEncoder # here we saw that Label encoder did not work for multiple column at once.




from sklearn.preprocessing import OneHotEncoder # used dummies instead



In [266]:
from sklearn.linear_model import LogisticRegression

In [267]:
regressor=LogisticRegression()

In [268]:
regressor.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [339]:
THRESHOLD = 0.1
preds = np.where(regressor.predict_proba(x_test)[:,1] > THRESHOLD, 1, 2)

In [340]:
y_pred=regressor.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2,
       1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1,
       1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2,
       1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2], dtype=int64)

In [341]:
from sklearn.metrics import confusion_matrix

In [342]:
cm=confusion_matrix(y_test,preds)

In [343]:
cm

array([[147,  32],
       [ 65,   6]], dtype=int64)

In [315]:
regressor.predict_proba(x_test)

array([[0.85370569, 0.14629431],
       [0.51327194, 0.48672806],
       [0.76781416, 0.23218584],
       [0.95487506, 0.04512494],
       [0.52872645, 0.47127355],
       [0.06024148, 0.93975852],
       [0.46966438, 0.53033562],
       [0.87790535, 0.12209465],
       [0.29142739, 0.70857261],
       [0.8519267 , 0.1480733 ],
       [0.94855782, 0.05144218],
       [0.89287245, 0.10712755],
       [0.73809476, 0.26190524],
       [0.57686075, 0.42313925],
       [0.87877892, 0.12122108],
       [0.17303492, 0.82696508],
       [0.82171934, 0.17828066],
       [0.65913211, 0.34086789],
       [0.41519524, 0.58480476],
       [0.65394105, 0.34605895],
       [0.66046004, 0.33953996],
       [0.42318317, 0.57681683],
       [0.89670858, 0.10329142],
       [0.93230836, 0.06769164],
       [0.84443104, 0.15556896],
       [0.9378386 , 0.0621614 ],
       [0.27254146, 0.72745854],
       [0.4438585 , 0.5561415 ],
       [0.81151997, 0.18848003],
       [0.39961639, 0.60038361],
       [0.

In [314]:
y_pred.shape

(250,)

In [344]:
cm2=confusion_matrix(y_test,y_pred)
cm2

array([[152,  27],
       [ 44,  27]], dtype=int64)

# conclusions-PCA can be used. Probability threshold can be tumed to decrease the number of false -ve as they are generally costly. Label Encoder and one hot encoder has been used differently via factorize and dummires dummies.