In [1]:
import pandas as pd
import numpy as np

In [2]:
regdata=pd.read_csv('regdata.csv')
meandata=pd.read_csv('meandata.csv')

In [11]:
regdata=regdata.drop(columns='Unnamed: 0')

In [12]:
regdata.head() # data in which missing values has been filled using the regression method

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0          1.0                3                1        1      2  
1         10.0                3                2        1      2  
2          2.0                3                1        1      2  
3          4.0                3                7        1      2  
4          1.0                3                1        1      2

In [13]:
meandata=meandata.drop(columns='Unnamed: 0')
meandata.head() # Data in which the missing values has been filled by imputation by mean

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0          1.0                3                1        1      2  
1         10.0                3                2        1      2  
2          2.0                3                1        1      2  
3          4.0                3                7        1      2  
4          1.0                3                1        1      2

# we will now compare which data is better for modelling

# Applying SVM and KNN with cross Validation. We will also see which one is better by finding the cross validation score

# 1. SVM for both data

In [18]:
x=regdata.iloc[:,1:10].values
y=regdata.iloc[:,10].values

In [23]:
X=meandata.iloc[:,1:10].values
Y=meandata.iloc[:,10].values

In [14]:
from sklearn.svm import SVC

In [15]:
classifier=SVC()

In [16]:
from sklearn.model_selection import cross_val_score

In [22]:
scores=cross_val_score(classifier,x,y,scoring='neg_mean_squared_error',cv=10)

scores

mse=-scores.mean()# mean squared error

rmse=np.sqrt(mse) # root mean squared error
rmse

0.4269669320781982

In [24]:
scoresmean=cross_val_score(classifier,X,Y,scoring='neg_mean_squared_error',cv=10)

scoresmean

mse=-scoresmean.mean()# mean squared error

rmse=np.sqrt(mse) # root mean squared error
rmse

0.4269669320781982

# 2 KNN for both data

In [25]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
Classifier=KNeighborsClassifier()

In [27]:
scores=cross_val_score(Classifier,x,y,scoring='neg_mean_squared_error',cv=10)

scores
mse=-scores.mean()# mean squared error

rmse=np.sqrt(mse) # root mean squared error
rmse

0.3620961727937072

In [28]:
scoresmean=cross_val_score(Classifier,X,Y,scoring='neg_mean_squared_error',cv=10)

scoresmean

mse=-scoresmean.mean()# mean squared error

rmse=np.sqrt(mse) # root mean squared error
rmse

0.3620961727937072

# Inference KNN classifier has better prediction capacity

# Now we will aplly SVM separately on both the datasets

In [38]:
classifier1=SVC(kernel='linear')
classifier1.fit(x,y)
y_pred1=classifier1.predict(x)

from sklearn.metrics import confusion_matrix
cm1=confusion_matrix(y,y_pred1)
cm1

array([[446,  12],
       [  8, 233]], dtype=int64)

In [37]:
classifier1=SVC(kernel='linear')
classifier1.fit(X,Y)
y_pred1=classifier1.predict(X)

from sklearn.metrics import confusion_matrix
cm1=confusion_matrix(Y,y_pred1)
cm1

array([[446,  12],
       [  9, 232]], dtype=int64)

# Finally applying KNN

In [39]:
classifier=KNeighborsClassifier(n_neighbors=5,weights='uniform',metric='euclidean')
classifier.fit(x,y)
y_pred=classifier.predict(x)
cm=confusion_matrix(y,y_pred)
cm

array([[448,  10],
       [  7, 234]], dtype=int64)

In [40]:
classifier=KNeighborsClassifier(n_neighbors=5,weights='uniform',metric='euclidean')
classifier.fit(X,Y)
y_pred=classifier.predict(X)
cm=confusion_matrix(Y,y_pred)
cm

array([[447,  11],
       [  7, 234]], dtype=int64)

# Conclusion- Imputation by regression was better