In [1]:

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd

In [288]:
data=pd.read_csv('uscrime.txt',delim_whitespace=True)

In [289]:
data

M  So    Ed   Po1   Po2     LF    M.F  Pop    NW     U1   U2  Wealth  \
0   15.1   1   9.1   5.8   5.6  0.510   95.0   33  30.1  0.108  4.1    3940   
1   14.3   0  11.3  10.3   9.5  0.583  101.2   13  10.2  0.096  3.6    5570   
2   14.2   1   8.9   4.5   4.4  0.533   96.9   18  21.9  0.094  3.3    3180   
3   13.6   0  12.1  14.9  14.1  0.577   99.4  157   8.0  0.102  3.9    6730   
4   14.1   0  12.1  10.9  10.1  0.591   98.5   18   3.0  0.091  2.0    5780   
5   12.1   0  11.0  11.8  11.5  0.547   96.4   25   4.4  0.084  2.9    6890   
6   12.7   1  11.1   8.2   7.9  0.519   98.2    4  13.9  0.097  3.8    6200   
7   13.1   1  10.9  11.5  10.9  0.542   96.9   50  17.9  0.079  3.5    4720   
8   15.7   1   9.0   6.5   6.2  0.553   95.5   39  28.6  0.081  2.8    4210   
9   14.0   0  11.8   7.1   6.8  0.632  102.9    7   1.5  0.100  2.4    5260   
10  12.4   0  10.5  12.1  11.6  0.580   96.6  101  10.6  0.077  3.5    6570   
11  13.4   0  10.8   7.5   7.1  0.595   97.2   47   5.9  0.083  3.1    5800   
12  12.8   0  11.3   6.7   6.0  0.624   97.2   28   1.0  0.077  2.5    5070   
13  13.5   0  11.7   6.2   6.1  0.595   98.6   22   4.6  0.077  2.7    5290   
14  15.2   1   8.7   5.7   5.3  0.530   98.6   30   7.2  0.092  4.3    4050   
15  14.2   1   8.8   8.1   7.7  0.497   95.6   33  32.1  0.116  4.7    4270   
16  14.3   0  11.0   6.6   6.3  0.537   97.7   10   0.6  0.114  3.5    4870   
17  13.5   1  10.4  12.3  11.5  0.537   97.8   31  17.0  0.089  3.4    6310   
18  13.0   0  11.6  12.8  12.8  0.536   93.4   51   2.4  0.078  3.4    6270   
19  12.5   0  10.8  11.3  10.5  0.567   98.5   78   9.4  0.130  5.8    6260   
20  12.6   0  10.8   7.4   6.7  0.602   98.4   34   1.2  0.102  3.3    5570   
21  15.7   1   8.9   4.7   4.4  0.512   96.2   22  42.3  0.097  3.4    2880   
22  13.2   0   9.6   8.7   8.3  0.564   95.3   43   9.2  0.083  3.2    5130   
23  13.1   0  11.6   7.8   7.3  0.574  103.8    7   3.6  0.142  4.2    5400   
24  13.0   0  11.6   6.3   5.7  0.641   98.4   14   2.6  0.070  2.1    4860   
25  13.1   0  12.1  16.0  14.3  0.631  107.1    3   7.7  0.102  4.1    6740   
26  13.5   0  10.9   6.9   7.1  0.540   96.5    6   0.4  0.080  2.2    5640   
27  15.2   0  11.2   8.2   7.6  0.571  101.8   10   7.9  0.103  2.8    5370   
28  11.9   0  10.7  16.6  15.7  0.521   93.8  168   8.9  0.092  3.6    6370   
29  16.6   1   8.9   5.8   5.4  0.521   97.3   46  25.4  0.072  2.6    3960   
30  14.0   0   9.3   5.5   5.4  0.535  104.5    6   2.0  0.135  4.0    4530   
31  12.5   0  10.9   9.0   8.1  0.586   96.4   97   8.2  0.105  4.3    6170   
32  14.7   1  10.4   6.3   6.4  0.560   97.2   23   9.5  0.076  2.4    4620   
33  12.6   0  11.8   9.7   9.7  0.542   99.0   18   2.1  0.102  3.5    5890   
34  12.3   0  10.2   9.7   8.7  0.526   94.8  113   7.6  0.124  5.0    5720   
35  15.0   0  10.0  10.9   9.8  0.531   96.4    9   2.4  0.087  3.8    5590   
36  17.7   1   8.7   5.8   5.6  0.638   97.4   24  34.9  0.076  2.8    3820   
37  13.3   0  10.4   5.1   4.7  0.599  102.4    7   4.0  0.099  2.7    4250   
38  14.9   1   8.8   6.1   5.4  0.515   95.3   36  16.5  0.086  3.5    3950   
39  14.5   1  10.4   8.2   7.4  0.560   98.1   96  12.6  0.088  3.1    4880   
40  14.8   0  12.2   7.2   6.6  0.601   99.8    9   1.9  0.084  2.0    5900   
41  14.1   0  10.9   5.6   5.4  0.523   96.8    4   0.2  0.107  3.7    4890   
42  16.2   1   9.9   7.5   7.0  0.522   99.6   40  20.8  0.073  2.7    4960   
43  13.6   0  12.1   9.5   9.6  0.574  101.2   29   3.6  0.111  3.7    6220   
44  13.9   1   8.8   4.6   4.1  0.480   96.8   19   4.9  0.135  5.3    4570   
45  12.6   0  10.4  10.6   9.7  0.599   98.9   40   2.4  0.078  2.5    5930   
46  13.0   0  12.1   9.0   9.1  0.623  104.9    3   2.2  0.113  4.0    5880   

    Ineq      Prob     Time  Crime  
0   26.1  0.084602  26.2011    791  
1   19.4  0.029599  25.2999   1635  
2   25.0  0.083401  24.3006    578  
3   16.7  0.015801  29.9012   1969  
4   17.4  0.041399  21.2998  

# Do one hot encoding on the x dataset before splitting into train test

In [290]:
from sklearn.preprocessing import OneHotEncoder
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [291]:
onehot=OneHotEncoder(categorical_features=[1])
x=onehot.fit_transform(x).toarray()
x.shape

(47, 16)

In [292]:
from sklearn.decomposition import  PCA
pca=PCA(n_components=5)

In [293]:
principal_components=pca.fit_transform(x)
principalDf=pd.DataFrame(principal_components,columns=['PC1','PC2','PC3','PC4','PC5'])

In [294]:
principalDf=pd.concat([principalDf,data['Crime']],axis=1)
principalDf

PC1         PC2        PC3        PC4       PC5  Crime
0   1313.899790   13.405071  10.061775  -3.933732 -1.765734    791
1   -315.857987  -27.188086   4.883406  -0.112238  2.407164   1635
2   2073.949760    6.271067  -2.532357  -2.505934 -0.820228    578
3  -1477.533069  102.463639  -3.380398  -6.614983  3.870208   1969
4   -525.951003  -25.588927  -1.898102  -2.427319 -0.941179   1234
5  -1635.931146  -31.293895   6.652890  -3.739208 -4.380603    682
6   -945.657262  -43.490045  12.681507  -4.323179 -2.481643    963
7    533.649284   20.096523   2.059787  -4.959431 -0.500238   1555
8   1043.835533   16.377767  10.633597  -1.114223 -1.342997    856
9     -5.867667  -31.113835  -7.072558  -2.703538  2.347532    705
10 -1316.836460   50.256310   6.774260   8.826411  0.921238   1674
11  -546.268327    4.325342   0.357881   7.751823 -0.793615    849
12   183.869984   -6.283740  -7.029027  12.496653  0.005376    511
13   -36.016020  -15.992091  -4.956966  -2.222506 -0.978282    664
14  1203.804632    6.697878 -11.592486  -1.965422  1.433250    798
15   983.931302    9.825617  14.549607  -4.955772 -1.384889    946
16   384.051488  -23.590594 -11.100337  -2.471296 -2.726260    539
17 -1055.972545  -17.818175  13.427244  -9.958788 -2.117643    929
18 -1016.327074    1.982798  -1.465339  -1.178504 -5.530240    750
19 -1006.595430   29.359197   2.126078  -3.726451  0.459398   1225
20  -316.156041   -5.990927  -3.537430  12.918511  1.092134    742
21  2374.007770   16.782388  17.551573   4.698231  0.753081    439
22   123.745685    7.724524  -2.429815  -1.325127 -2.025485   1216
23  -145.842816  -32.731908  -4.470430  -5.358150  3.056611    968
24   394.025415  -19.076082  -9.038598  -0.632089 -1.074727    523
25 -1485.671722  -51.170587  11.643730  -3.441057  6.885927   1993
26  -385.830872  -35.504708  -3.032649   6.765656 -3.794056    342
27  -115.839608  -28.088712   1.539721   1.400722  3.301595   1216
28 -1117.709748  118.537751  -4.455822  -0.695481 -0.632290   1043
29  1293.706089   25.691639   4.509531  -1.919505  0.345379    696
30   724.087128  -23.487584 -11.393920  -0.429868  4.620199    373
31  -916.832838   49.499787  -1.065391   0.042252 -1.103785    754
32   633.949131   -6.312234  -3.854008   0.595331 -0.573551   1072
33  -635.945415  -26.953225  -2.107248  -1.817610 -0.868348    923
34  -467.083392   71.205114  -5.105592   5.407562 -1.482221    653
35  -335.869084  -30.071295   2.524338  20.456158 -0.983176   1272
36  1434.025512    6.715055  16.019206   0.705044  0.868195    831
37  1004.068968  -19.507721 -12.741298  -5.553692  2.654227    566
38  1303.774861   15.162055  -2.991025   0.120873 -1.453443    826
39   373.098020   63.613847  -6.244316  -2.288889  2.199386   1151
40  -645.829633  -35.398645   0.214239   7.231399 -0.225048    880
41   364.130574  -30.468318 -12.342579  -8.321675 -4.555750    542
42   293.842370    8.141293   9.065772   2.446153  2.588583    823
43  -966.035974  -19.034582   2.343890   4.682765  2.257281   1030
44   683.979435   -9.415563  -6.612046   9.086634 -0.074064    455
45  -676.206149   -6.061733  -5.048827  -8.345119 -1.018339    508
46  -625.765449  -42.501451  -2.121468  -6.591392  3.561066    849

In [295]:
X=principalDf.iloc[:,:-1].values
Y=principalDf.iloc[:,-1].values

In [296]:
from sklearn.model_selection import train_test_split

In [297]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=.2)

In [298]:
from sklearn.preprocessing import StandardScaler

In [299]:
sc_x=StandardScaler()

In [300]:
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [301]:
from sklearn.linear_model import LinearRegression

In [302]:
regressor=LinearRegression()

In [303]:
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [304]:
y_pred=regressor.predict(x_test)

In [305]:
y_pred

array([ 582.64004142,  891.00294687,  953.50704458, 1177.99299402,
       1100.02388046, 1135.77701918,  650.54195824, 1662.20900971,
        967.0978986 ,  551.15286488])

In [306]:
y_test

array([ 455,  696,  373,  929,  968, 1151,  523, 1993,  705, 1272],
      dtype=int64)

In [307]:
from sklearn import metrics

In [308]:
#rmse = metrics.mean_squared_error(y_test, y_pred)
r2 = metrics.r2_score(y_test, y_pred)
#rmse

In [309]:
r2

0.4353514904215374

In [310]:
print('Slope:' ,regressor.coef_)
print('Intercept:', regressor.intercept_)

Slope: [-146.45433183   89.56176764   83.01167547  -78.61478422  152.93184927]
Intercept: 904.7027027027027


In [311]:
import statsmodels.api as sm

In [312]:
x_train=sm.add_constant(x_train)
model=sm.OLS(y_train,x_train).fit()
x_test = sm.add_constant(x_test)
y_pred=model.predict(x_test)
y_pred

array([ 582.64004142,  891.00294687,  953.50704458, 1177.99299402,
       1100.02388046, 1135.77701918,  650.54195824, 1662.20900971,
        967.0978986 ,  551.15286488])

In [313]:
y_test

array([ 455,  696,  373,  929,  968, 1151,  523, 1993,  705, 1272],
      dtype=int64)

In [314]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.486
Model:                            OLS   Adj. R-squared:                  0.404
Method:                 Least Squares   F-statistic:                     5.871
Date:                Fri, 05 Apr 2019   Prob (F-statistic):           0.000629
Time:                        15:58:50   Log-Likelihood:                -257.91
No. Observations:                  37   AIC:                             527.8
Df Residuals:                      31   BIC:                             537.5
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        904.7027     46.276     19.550      0.000     810.322     999.084
x1          -146.4543     47.350     -3.093      0.004    -243.025     -49.884
x2            89.5618     47.106      1.901      0.067      -6.511     185.634
x3            83.0117     47.159      1.760      0.088     -13.170     179.193
x4           -78.6148     46.892     -1.677      0.104    -174.252      17.022
x5           152.9318     47.262      3.236      0.003      56.541     249.323
==============================================================================
Omnibus:                        1.531   Durbin-Watson:                   1.796
Prob(Omnibus):                  0.465   Jarque-Bera (JB):                1.315
Skew:                           0.446   Prob(JB):                        0.518
Kurtosis:                       2.760   Cond. No.                         1.30
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""