# Just validating which model would be best out of SVM & KNN. No test done.

In [96]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [97]:
dataset= pd.read_csv('credit_card_data-headers.txt',delim_whitespace=True)
dataset.head()

A1     A2     A3    A8  A9  A10  A11  A12  A14  A15  R1
0   1  30.83  0.000  1.25   1    0    1    1  202    0   1
1   0  58.67  4.460  3.04   1    0    6    1   43  560   1
2   0  24.50  0.500  1.50   1    1    0    1  280  824   1
3   1  27.83  1.540  3.75   1    0    5    0  100    3   1
4   1  20.17  5.625  1.71   1    1    0    1  120    0   1

In [98]:
x=dataset.iloc[:,[0,1,2,3,4,5,6,7,8,9]].values
y=dataset.iloc[:,10].values

In [100]:
x

array([[ 0.67090302, -0.06250497, -0.96236739, ...,  0.92625836,
         0.13030676, -0.19307375],
       [-1.49052839,  2.26279958, -0.0738244 , ...,  0.92625836,
        -0.81506958, -0.08631163],
       [-1.49052839, -0.59121107, -0.86275494, ...,  0.92625836,
         0.59407629, -0.03598091],
       ...,
       [-1.49052839, -0.52856817,  1.72716857, ..., -1.07961239,
         0.11841524, -0.19288311],
       [ 0.67090302, -1.14079814, -0.92152628, ...,  0.92625836,
         0.59407629, -0.05008876],
       [ 0.67090302,  0.28578957, -0.2899834 , ..., -1.07961239,
        -1.0707374 , -0.19307375]])

In [101]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [4]:
#scaling the data
from sklearn.preprocessing import StandardScaler

In [23]:
sc=StandardScaler()
sc.fit(x)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [24]:
x=sc.fit_transform(x)

# Generating classifier in a different manner

In [69]:
from sklearn import svm,neighbors

In [78]:
svmclassifier=svm.SVC(kernel='linear')
knnclassifier=neighbors.KNeighborsClassifier(n_neighbors=5,metric='minkowski')

# Using cross validation package to split data into 10 folds and obtaining their respective scores

In [94]:
from sklearn.model_selection import cross_val_score
scores_svm=cross_val_score(svmclassifier,x,y,cv=10)
scores_knn=cross_val_score(knnclassifier,x,y,cv=10)
scores_svm
# cross validate is splitting data RANDOMLY, fitting to the model and then prediting for the validatae part of the data, i.e the 10 th part
# the scores generated seem to be on 10 the part

array([0.43939394, 0.84848485, 0.96969697, 0.98484848, 0.98484848,
       0.98484848, 0.92307692, 0.58461538, 0.96875   , 0.9375    ])

In [82]:
scores_knn

array([0.48484848, 0.84848485, 0.93939394, 0.98484848, 0.92424242,
       0.92424242, 0.83076923, 0.64615385, 0.9375    , 0.84375   ])

In [87]:
scores_knn.mean()

0.8364233682983684

In [88]:
scores_svm.mean()

0.862606351981352

# Step to find the accuracy
# The mean score and the 95% confidence interval of the score estimate are hence given by 2sigma:

In [91]:
print("Accuracy: %0.2f (+/- %0.2f)" % (scores_knn.mean(), scores_knn.std() * 2))

Accuracy: 0.84 (+/- 0.30)


# Conclusion is that we can use cross_val_score to find which model is the bes. However I wanted the average of all the iterations for a single model into one model which I couldn't find how to do.

# One thought: While doing each of the 10 simulations the svm got trained from all 10. and now when you agre going to run with test data, the model will have to be trained again on the whole dataset.