In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
import statsmodels.api as sm

In [38]:
dataset=pd.read_csv('uscrime.txt',delim_whitespace=True)

In [39]:
dataset.head()

M  So    Ed   Po1   Po2     LF    M.F  Pop    NW     U1   U2  Wealth  \
0  15.1   1   9.1   5.8   5.6  0.510   95.0   33  30.1  0.108  4.1    3940   
1  14.3   0  11.3  10.3   9.5  0.583  101.2   13  10.2  0.096  3.6    5570   
2  14.2   1   8.9   4.5   4.4  0.533   96.9   18  21.9  0.094  3.3    3180   
3  13.6   0  12.1  14.9  14.1  0.577   99.4  157   8.0  0.102  3.9    6730   
4  14.1   0  12.1  10.9  10.1  0.591   98.5   18   3.0  0.091  2.0    5780   

   Ineq      Prob     Time  Crime  
0  26.1  0.084602  26.2011    791  
1  19.4  0.029599  25.2999   1635  
2  25.0  0.083401  24.3006    578  
3  16.7  0.015801  29.9012   1969  
4  17.4  0.041399  21.2998   1234

# To handle categorical data we need to encode them as well.

In [55]:

#dataset=dataset.drop('Pop',axis=1), it was previously dropped because the coefficient associated with this parameter was too samll.(sklearn linear regression model)


In [40]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [8]:
dataset

M  So    Ed   Po1   Po2     LF    M.F    NW     U1   U2  Wealth  Ineq  \
0   15.1   1   9.1   5.8   5.6  0.510   95.0  30.1  0.108  4.1    3940  26.1   
1   14.3   0  11.3  10.3   9.5  0.583  101.2  10.2  0.096  3.6    5570  19.4   
2   14.2   1   8.9   4.5   4.4  0.533   96.9  21.9  0.094  3.3    3180  25.0   
3   13.6   0  12.1  14.9  14.1  0.577   99.4   8.0  0.102  3.9    6730  16.7   
4   14.1   0  12.1  10.9  10.1  0.591   98.5   3.0  0.091  2.0    5780  17.4   
5   12.1   0  11.0  11.8  11.5  0.547   96.4   4.4  0.084  2.9    6890  12.6   
6   12.7   1  11.1   8.2   7.9  0.519   98.2  13.9  0.097  3.8    6200  16.8   
7   13.1   1  10.9  11.5  10.9  0.542   96.9  17.9  0.079  3.5    4720  20.6   
8   15.7   1   9.0   6.5   6.2  0.553   95.5  28.6  0.081  2.8    4210  23.9   
9   14.0   0  11.8   7.1   6.8  0.632  102.9   1.5  0.100  2.4    5260  17.4   
10  12.4   0  10.5  12.1  11.6  0.580   96.6  10.6  0.077  3.5    6570  17.0   
11  13.4   0  10.8   7.5   7.1  0.595   97.2   5.9  0.083  3.1    5800  17.2   
12  12.8   0  11.3   6.7   6.0  0.624   97.2   1.0  0.077  2.5    5070  20.6   
13  13.5   0  11.7   6.2   6.1  0.595   98.6   4.6  0.077  2.7    5290  19.0   
14  15.2   1   8.7   5.7   5.3  0.530   98.6   7.2  0.092  4.3    4050  26.4   
15  14.2   1   8.8   8.1   7.7  0.497   95.6  32.1  0.116  4.7    4270  24.7   
16  14.3   0  11.0   6.6   6.3  0.537   97.7   0.6  0.114  3.5    4870  16.6   
17  13.5   1  10.4  12.3  11.5  0.537   97.8  17.0  0.089  3.4    6310  16.5   
18  13.0   0  11.6  12.8  12.8  0.536   93.4   2.4  0.078  3.4    6270  13.5   
19  12.5   0  10.8  11.3  10.5  0.567   98.5   9.4  0.130  5.8    6260  16.6   
20  12.6   0  10.8   7.4   6.7  0.602   98.4   1.2  0.102  3.3    5570  19.5   
21  15.7   1   8.9   4.7   4.4  0.512   96.2  42.3  0.097  3.4    2880  27.6   
22  13.2   0   9.6   8.7   8.3  0.564   95.3   9.2  0.083  3.2    5130  22.7   
23  13.1   0  11.6   7.8   7.3  0.574  103.8   3.6  0.142  4.2    5400  17.6   
24  13.0   0  11.6   6.3   5.7  0.641   98.4   2.6  0.070  2.1    4860  19.6   
25  13.1   0  12.1  16.0  14.3  0.631  107.1   7.7  0.102  4.1    6740  15.2   
26  13.5   0  10.9   6.9   7.1  0.540   96.5   0.4  0.080  2.2    5640  13.9   
27  15.2   0  11.2   8.2   7.6  0.571  101.8   7.9  0.103  2.8    5370  21.5   
28  11.9   0  10.7  16.6  15.7  0.521   93.8   8.9  0.092  3.6    6370  15.4   
29  16.6   1   8.9   5.8   5.4  0.521   97.3  25.4  0.072  2.6    3960  23.7   
30  14.0   0   9.3   5.5   5.4  0.535  104.5   2.0  0.135  4.0    4530  20.0   
31  12.5   0  10.9   9.0   8.1  0.586   96.4   8.2  0.105  4.3    6170  16.3   
32  14.7   1  10.4   6.3   6.4  0.560   97.2   9.5  0.076  2.4    4620  23.3   
33  12.6   0  11.8   9.7   9.7  0.542   99.0   2.1  0.102  3.5    5890  16.6   
34  12.3   0  10.2   9.7   8.7  0.526   94.8   7.6  0.124  5.0    5720  15.8   
35  15.0   0  10.0  10.9   9.8  0.531   96.4   2.4  0.087  3.8    5590  15.3   
36  17.7   1   8.7   5.8   5.6  0.638   97.4  34.9  0.076  2.8    3820  25.4   
37  13.3   0  10.4   5.1   4.7  0.599  102.4   4.0  0.099  2.7    4250  22.5   
38  14.9   1   8.8   6.1   5.4  0.515   95.3  16.5  0.086  3.5    3950  25.1   
39  14.5   1  10.4   8.2   7.4  0.560   98.1  12.6  0.088  3.1    4880  22.8   
40  14.8   0  12.2   7.2   6.6  0.601   99.8   1.9  0.084  2.0    5900  14.4   
41  14.1   0  10.9   5.6   5.4  0.523   96.8   0.2  0.107  3.7    4890  17.0   
42  16.2   1   9.9   7.5   7.0  0.522   99.6  20.8  0.073  2.7    4960  22.4   
43  13.6   0  12.1   9.5   9.6  0.574  101.2   3.6  0.111  3.7    6220  16.2   
44  13.9   1   8.8   4.6   4.1  0.480   96.8   4.9  0.135  5.3    4570  24.9   
45  12.6   0  10.4  10.6   9.7  0.599   98.9   2.4  0.078  2.5    5930  17.1   
46  13.0   0  12.1   9.0   9.1  0.623  104.9   2.2  0.113  4.0    5880  16.0   

        Prob     Time  Crime  
0   0.084602  26.2011    791  
1   0.029599  25.2999   1635  
2   0.083401  24.3006    578  
3   0.015801  29.9012   1969  
4   0.04139

In [9]:
x[1][1]

0.0

In [41]:
from sklearn.preprocessing import OneHotEncoder

In [42]:
onehotencoder=OneHotEncoder(categorical_features=[1])
x=onehotencoder.fit_transform(x).toarray()

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25)

In [45]:
# feature scaling required, this can also be done prior to the splitting into test, train

In [46]:
from sklearn.preprocessing import StandardScaler

In [47]:
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [48]:
from sklearn.linear_model import LinearRegression

In [18]:
regressor=LinearRegression()

In [19]:
m=regressor.fit(x_train,y_train)

In [20]:
y_pred=regressor.predict(x_test)

In [21]:
y_pred.astype(int)

array([1389,  544,  426,  566,  945, 1221, 1157,  946,  916,  775,  765,
        602])

In [22]:
y_test

array([1555,  742,  373,  542,  826,  750,  823,  508, 1674, 1072,  754,
        849], dtype=int64)

In [23]:
from sklearn import metrics

In [24]:
rmse = metrics.mean_squared_error(y_test, y_pred)
r2 = metrics.r2_score(y_test, y_pred)
rmse

111148.94269629575

In [25]:
r2

0.2111700641047921

In [26]:
print('Slope:' ,regressor.coef_)
print('Intercept:', regressor.intercept_)

Slope: [  14.86830047  -14.86830047  177.47455399  226.22537559  979.39458617
 -692.81622516  -78.24818895   35.10689332   54.02312083 -118.80981958
  157.05828816   47.70303178  229.64562695 -154.00612355 -129.91503458]
Intercept: 916.3142857142855


In [27]:
# Now we are gonna use statsmodel linear regeression because we couldn't see the p-values in the skleearn packagew

In [49]:
x_train=sm.add_constant(x_train)

In [141]:
model=sm.OLS(y_train,x_train).fit()
x_test = sm.add_constant(x_test)
y_pred=model.predict(x_test)
y_pred

array([1125.74160035,  811.23454704, 1721.90556212,  820.80577175,
        434.01268121,  821.87056453,  720.75687755, 1263.80169144,
        933.8777922 , 1218.21126306,  208.04737273,  589.25453634])

In [142]:
y_test

array([1234,  511, 1969,  653,  566,  455,  929, 1555, 1216,  750,  578,
        856], dtype=int64)

In [51]:
m=model.summary()

In [52]:
m

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.844
Model:                            OLS   Adj. R-squared:                  0.722
Method:                 Least Squares   F-statistic:                     6.874
Date:                Thu, 04 Apr 2019   Prob (F-statistic):           7.80e-05
Time:                        10:50:03   Log-Likelihood:                -222.77
No. Observations:                  35   AIC:                             477.5
Df Residuals:                      19   BIC:                             502.4
Df Model:                          15                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        893.3429     32.255     27.696      0.000     825.832     960.854
x1            -3.3116     43.885     -0.075      0.941     -95.163      88.540
x2             3.3116     43.885      0.075      0.941     -88.540      95.163
x3           148.2717     68.392      2.168      0.043       5.126     291.418
x4           237.3085     80.948      2.932      0.009      67.882     406.735
x5           474.1561    294.316      1.611      0.124    -141.855    1090.167
x6          -250.6535    304.695     -0.823      0.421    -888.388     387.081
x7           -22.8197     61.861     -0.369      0.716    -152.297     106.657
x8             3.5147     71.784      0.049      0.961    -146.731     153.761
x9           -62.7109     56.940     -1.101      0.284    -181.887      56.465
x10          -18.0153     81.234     -0.222      0.827    -188.040     152.009
x11         -102.5139     97.013     -1.057      0.304    -305.564     100.536
x12          186.0261     79.795      2.331      0.031      19.014     353.038
x13          126.1251    151.404      0.833      0.415    -190.767     443.017
x14          299.2272    114.988      2.602      0.018      58.555     539.899
x15         -100.5243     78.924     -1.274      0.218    -265.714      64.666
x16           18.1236     68.179      0.266      0.793    -124.576     160.823
==============================================================================
Omnibus:                       14.407   Durbin-Watson:                   2.086
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               17.267
Skew:                           1.172   Prob(JB):                     0.000178
Kurtosis:                       5.518   Cond. No.                     5.00e+16
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.83e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [56]:
# We can remove the parameters whose p values are greater than .05
#These coefficients are x1,x2,x5 to x11,x13,x15,x16.
#Lets load the data again and do this 

In [145]:
dataset1=pd.read_csv('uscrime.txt',delim_whitespace=True)

In [146]:
dataset1.head()#M,Ed,U1,Wealth

M  So    Ed   Po1   Po2     LF    M.F  Pop    NW     U1   U2  Wealth  \
0  15.1   1   9.1   5.8   5.6  0.510   95.0   33  30.1  0.108  4.1    3940   
1  14.3   0  11.3  10.3   9.5  0.583  101.2   13  10.2  0.096  3.6    5570   
2  14.2   1   8.9   4.5   4.4  0.533   96.9   18  21.9  0.094  3.3    3180   
3  13.6   0  12.1  14.9  14.1  0.577   99.4  157   8.0  0.102  3.9    6730   
4  14.1   0  12.1  10.9  10.1  0.591   98.5   18   3.0  0.091  2.0    5780   

   Ineq      Prob     Time  Crime  
0  26.1  0.084602  26.2011    791  
1  19.4  0.029599  25.2999   1635  
2  25.0  0.083401  24.3006    578  
3  16.7  0.015801  29.9012   1969  
4  17.4  0.041399  21.2998   1234

In [147]:
dataset1=dataset1[['M','Ed','U2','Wealth','Ineq','Crime']]


In [174]:
dataset1.head()

M    Ed   U2  Wealth  Ineq  Crime
0  15.1   9.1  4.1    3940  26.1    791
1  14.3  11.3  3.6    5570  19.4   1635
2  14.2   8.9  3.3    3180  25.0    578
3  13.6  12.1  3.9    6730  16.7   1969
4  14.1  12.1  2.0    5780  17.4   1234

In [149]:
X=dataset1.iloc[:,0:5].values
Y=dataset1.iloc[:,-1].values


In [150]:
# Scaling the data after splitting into tests and train

In [151]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=.25)

In [152]:
X_test.shape,X_train.shape,Y_test.shape,Y_train.shape

((12, 5), (35, 5), (12,), (35,))

In [153]:
from sklearn.preprocessing import StandardScaler

In [154]:
#sc_x=StandardScaler()
#X_train=sc_x.fit_transform(X_train)
#X_test=sc_x.transform(X_test)

In [155]:
# we have our package import done
X_test = sm.add_constant(X_test)

In [156]:
X_train=sm.add_constant(X_train)

In [157]:
Model=sm.OLS(Y_train,X_train).fit()
Y_pred=Model.predict(X_test)

In [158]:
Y_pred

array([ 525.79799796,  860.11081845,  970.85566721, 1131.74001239,
       1031.11068007,  988.41356929,  728.50452888,  916.30242559,
       1226.75182469, 1082.38196219, 1032.45435297,  843.86934001])

In [159]:
Model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.539
Model:                            OLS   Adj. R-squared:                  0.459
Method:                 Least Squares   F-statistic:                     6.775
Date:                Thu, 04 Apr 2019   Prob (F-statistic):           0.000270
Time:                        11:59:12   Log-Likelihood:                -247.44
No. Observations:                  35   AIC:                             506.9
Df Residuals:                      29   BIC:                             516.2
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -7524.7003   1732.055     -4.344      0.000   -1.11e+04   -3982.249
x1           126.1991     59.592      2.118      0.043       4.319     248.079
x2           152.5892     79.461      1.920      0.065      -9.927     315.106
x3           108.3725     69.329      1.563      0.129     -33.420     250.165
x4             0.5202      0.122      4.259      0.000       0.270       0.770
x5           103.7402     30.225      3.432      0.002      41.923     165.558
==============================================================================
Omnibus:                        3.982   Durbin-Watson:                   2.746
Prob(Omnibus):                  0.137   Jarque-Bera (JB):                2.650
Skew:                           0.619   Prob(JB):                        0.266
Kurtosis:                       3.534   Cond. No.                     1.78e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.78e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

# Conclusion- I started with multiple Linear Regression in Sklearn package and removed the insignificant variable by looking at its coefficients(slope) but there I couldn't find the p-value, so I switched to the stats model OLS, there I trained the model on the whole dataset with scaling and One Hot encoding for the categorical data. 
 # Here I found several variables with p-value> .05, that means they are insignificant(not all the time), I removed them as well and then trained the model again, later I found those variable had p-value>.05. and r2 was too small. Not a good success.

In [163]:
# Let us now use cross validation also
from sklearn import cross_validation

C:\Users\SAURABH\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [162]:
regressor=LinearRegression()

In [164]:
scores=cross_validation.cross_val_score(regressor,x_train,y_train,scoring='mean_squared_error',cv=10)

C:\Users\SAURABH\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\SAURABH\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\SAURABH\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\SAURABH\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\SAURABH\Anacond

In [165]:
scores

array([ -59522.15713173,  -27169.37483577,  -55431.06730478,
        -25740.24558352,  -60618.11831045,  -27108.67138296,
        -35590.47540344, -214801.4154711 ,  -86327.40235301,
        -57907.74454094])

In [169]:
mse=-scores.mean()# mean squared error

rmse=np.sqrt(mse) # root mean squared error
rmse

# how to use Cross validation to compare the model. We can compare Linear regression models(classification and regression models) with differen variables. Model1- can have different set of variable and the model2- will have other variables. we can find the model with the least mean of the root mean squared error.

